### ISSUE TITLE
Version solving failed, please update http package and enable null safety.

### ISSUE THREAD

**Issue by MominRaza** [long1eu/google_sign_in_dart#19]
``` terminal
[yourapp] flutter pub add google_sign_in_dartio
The current Dart SDK version is 3.3.0-142.0.dev.

Because google_sign_in_dartio >=0.1.0 <0.2.2+1 depends on http ^0.13.3 and google_sign_in_dartio <0.1.0 doesn't support null safety, google_sign_in_dartio <0.2.2+1 requires http ^0.13.3.
And because google_sign_in_dartio >=0.2.2+1 depends on http ^0.13.5, every version of google_sign_in_dartio requires http ^0.13.3.
So, because yourapp depends on both http ^1.1.0 and google_sign_in_dartio any, version solving failed.

The lower bound of "sdk: '>=2.1.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
exit code 65
```

**Comment by nilsreichardt** [comment]
I created a PR to fix this issue: #20 

Until this PR is merged, you can use in your `pubspec.yaml` as a workaround:

```yaml
google_sign_in_dartio:
    git:
      url: https://github.com/nilsreichardt/google_sign_in_dart
      ref: aa8dd1d7a43516b0815a92f0b5a470452ebb2efc
```
